### ISSUE TITLE
Text is cut off.

### ISSUE THREAD

**Issue by elijahlrc** [brakmic/Julia-Cheat-Sheet#1]
Lines don't wrap and get cut off. (You probably already know this, sorry)

**Comment by brakmic** [comment]
A more detailed info would be helpful.
Browser, OS etc.
Maybe a screenshot.

**Comment by brakmic** [comment]
Added word-wrapping to all boxes.

https://github.com/brakmic/Julia-Cheat-Sheet/commit/a6bab168c1e93b04c7df11bb652e989151b48a5d

**Comment by elijahlrc** [comment]
Here is a screenshot.
The problem occurred using chrome.
Sorry for the crappy issue report.
![image](https://cloud.githubusercontent.com/assets/5499184/21115557/b32c7cee-c066-11e6-8d4a-d871c15b4ec3.png)

**Comment by brakmic** [comment]
No problem.

I updated the CSS. Now the word-wrap should automatically break words if they're too long. Could you, please, test it in your browser. 

Thanks!

**Comment by elijahlrc** [comment]
Still getting an issue, its not the text itself, its the whole purple box (don't know what else to call it) that is getting cut off. In the above screenshot, the box labeled "What is" is being drawn behind the "Types" box.

**Comment by elijahlrc** [comment]
As I scale the window to be smaller the text boxes will overlap more and more until the page snaps to having one fewer box per row. The issue is that this snap happens well after the text boxes occlude each other.

**Comment by brakmic** [comment]
Yes, there's a problem with the styling. I'll now add a few media queries to adapt the styling according to  the local resolution. Will take a few moments until it gets complete.

**Comment by brakmic** [comment]
The media query is active now. It'll use 35em width for resolutions less than 1500px. Could you, please, test it?

**Comment by elijahlrc** [comment]
It works much better at lower screen widths, but there are still issues when there are 3 or 4 boxes side by side:
![image](https://cloud.githubusercontent.com/assets/5499184/21116159/537131f2-c069-11e6-9a9c-4a82168360b3.png)
![image](https://cloud.githubusercontent.com/assets/5499184/21116178/6cd2db8c-c069-11e6-8353-c701aafa4084.png)
This is maybe less of a problem as most of the time browser windows are not that wide.

**Comment by brakmic** [comment]
I could put extra media queries for such monitors. What's the resolution you have?

**Comment by brakmic** [comment]
It should now work well across all of monitors/resolutions.

**Comment by BenjaminBorn** [comment]
Sorry for resurrecting this old issue but I encounter a similar issue using Safari on a 5k iMac (5120 x 2880 resolution). However, it's not that text is cut off but that it flows over the border. It seems to only be a problem with quoted code.

Btw, thanks for this awesome cheat sheet!

<img width="596" alt="screenshot 2017-12-16 12 00 15" src="https://user-images.githubusercontent.com/12073629/34069901-37d73108-e25a-11e7-865a-205de847fa40.png">
